[package]
name = "talksage-asr"
description = "TalkSage v2 streaming ASR engines (sherpa-onnx based)"
version.workspace = true
edition.workspace = true
license.workspace = true

[target.'cfg(not(target_os = "macos"))'.dependencies]
libloading = "0.8"

[dependencies]
talksage-core = { path = "../talksage-core" }
anyhow = { workspace = true }
sherpa-onnx = "1.13"
log = "0.4"
ureq = { version = "2", features = ["proxy-from-env"] }
bzip2 = "0.4"
tar = "0.4"
